# Set up the environment
FROM node:14.4.0

# Specify a working directory in container
WORKDIR /usr/src/app

# Install tools & dependencies
COPY ./package*.json ./
RUN npm install

# Copy the application source code & other libraries
COPY ./ ./

# Define a default command to be run in container
CMD [ "npm", "run", "start" ]
